
clean:
	rm -f *.O *.xwam* core *~ *.bak .#* *.dll *.exe *.obj *.lib *.def *.exp
	rm -f */*.O */*.xwam* */core */*~ */*.bak */.#* */*.dll */*.exe */*.obj */*.lib */*.def */*.exp */temp
	rm -f */*/*.O */*/*.xwam* */*/core */*/*~ */*/*.bak */*/*/.#* */*/*.dll */*/*.exe */*/*.obj */*/*.lib */*/*.def */*/*.exp */*/temp
	rm -f ../XSB/packages/*.xwam* ../XSB/packages/*/*.xwam* ../XSB/packages/*/*/*.xwam* 
