/*
** This program has been automatically generated by the
** second-level foreign language interface of the
** XSB System
*/

#include <stdio.h>
#include "/Users/macuser/XSB/XSB/emu/cinterf.h"
#include "/Users/macuser/XSB/XSB/emu/context.h"

/* New Definition: paddints/3(a:input,b:input,retval:output) from int add_integers/2(int a,int b). */
int add_integers(int a, int b);
DllExport int call_conv paddints(CTXTdecl)
{
   prolog_term aIn;
   prolog_int  a;
   prolog_term bIn;
   prolog_int  b;
   prolog_term retvalOut;
   prolog_int retval;
   aIn = extern_reg_term(1);
   if (!is_int(aIn)) return FALSE;
   a = extern_p2c_int(aIn);
   bIn = extern_reg_term(2);
   if (!is_int(bIn)) return FALSE;
   b = extern_p2c_int(bIn);
   retvalOut = extern_reg_term(3);
   if(!is_var(retvalOut)) return FALSE;
   retval =   add_integers(a, b);
   extern_c2p_int(retval,retvalOut);
   return TRUE;
}

/* New Definition: paddfloats/3(a:input,b:input,retval:output) from float add_floats/2(float a,float b). */
double add_floats(double a, double b);
DllExport int call_conv paddfloats(CTXTdecl)
{
   prolog_term aIn;
   double a;
   prolog_term bIn;
   double b;
   prolog_term retvalOut;
   double retval;
   aIn = extern_reg_term(1);
   if (!is_float(aIn)) return FALSE;
   a = extern_p2c_float(aIn);
   bIn = extern_reg_term(2);
   if (!is_float(bIn)) return FALSE;
   b = extern_p2c_float(bIn);
   retvalOut = extern_reg_term(3);
   if(!is_var(retvalOut)) return FALSE;
   retval =   add_floats(a, b);
   extern_c2p_float(retval,retvalOut);
   return TRUE;
}

/* New Definition: pswapints/4(a:input,b:input,a:output,b:output) from void swap_ints/2(intptr a,intptr b). */
void swap_ints(int * a, int * b);
DllExport int call_conv pswapints(CTXTdecl)
{
   prolog_term aIn, aOut;
   prolog_int a;
   prolog_term bIn, bOut;
   prolog_int b;
   aIn = extern_reg_term(1);
   if (!is_int(aIn)) return FALSE;
   a = extern_p2c_int(aIn);
   aOut = extern_reg_term(3);
   if(!is_var(aOut)) return FALSE;
   bIn = extern_reg_term(2);
   if (!is_int(bIn)) return FALSE;
   b = extern_p2c_int(bIn);
   bOut = extern_reg_term(4);
   if(!is_var(bOut)) return FALSE;
   swap_ints(&a, &b);
   extern_c2p_int(a,aOut);
   extern_c2p_int(b,bOut);
   return TRUE;
}

/* New Definition: psort/2(a:input,a:output) from void sort/1(string(80) a). */
void sort(char * a);
DllExport int call_conv psort(CTXTdecl)
{
   prolog_term aIn,aOut;
   char a[80+1],*aTemp;
   aIn = extern_reg_term(1);
   if (!is_string(aIn)) return FALSE;
   aTemp = extern_p2c_string(aIn);
   strncpy(a,aTemp,80);
   a[80] = (char) NULL;
   aOut = extern_reg_term(2);
   if(!is_var(aOut)) return FALSE;
   sort(a);
   extern_c2p_string(a,aOut);
   return TRUE;
}

/* New Definition: plcsort/2(a:input,a:output) from void sort/1(chars(80) a). */
void sort(char * a);
DllExport int call_conv plcsort(CTXTdecl)
{
   prolog_term aIn,aOut;
   char a[80+1];
   int asize;
   aIn = extern_reg_term(1);
   if (!is_charlist(aIn,&asize)) return FALSE;
   extern_p2c_chars(aIn,a,80);
   a[80] = (char) NULL;
   aOut = extern_reg_term(2);
   if(!is_var(aOut)) return FALSE;
   sort(a);
   extern_c2p_chars(a,3,aOut);
   return TRUE;
}

